package com.michaelhoffmantech.recipemanager.recipedataservice.domain;
// Generated Feb 13, 2017 4:02:01 PM by Hibernate Tools 5.2.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Category generated by hbm2java
 */
@Entity
@Table(name = "category")
public class Category implements java.io.Serializable {

   private static final long serialVersionUID = 2485576496694675489L;

   private Integer categoryId;
   private String categoryName;
   private String createdBy;
   private Date createdTimestamp;
   private Set<RecipeCategory> recipeCategories = new HashSet<RecipeCategory>(0);

   public Category() {
   }

   public Category(Integer categoryId, String categoryName, String createdBy,
         Date createdTimestamp) {
      this.categoryId = categoryId;
      this.categoryName = categoryName;
      this.createdBy = createdBy;
      this.createdTimestamp = createdTimestamp;
   }

   public Category(Integer categoryId, String categoryName, String createdBy,
         Date createdTimestamp, Set<RecipeCategory> recipeCategories) {
      this.categoryId = categoryId;
      this.categoryName = categoryName;
      this.createdBy = createdBy;
      this.createdTimestamp = createdTimestamp;
      this.recipeCategories = recipeCategories;
   }

   @Id
   @SequenceGenerator(name = "category_category_id_seq",
         sequenceName = "category_category_id_seq", allocationSize = 1)
   @GeneratedValue(strategy = GenerationType.SEQUENCE,
         generator = "category_category_id_seq")
   @Column(name = "category_id", unique = true, nullable = false)
   public Integer getCategoryId() {
      return this.categoryId;
   }

   public void setCategoryId(Integer categoryId) {
      this.categoryId = categoryId;
   }

   @Column(name = "category_name", nullable = false, length = 200)
   public String getCategoryName() {
      return this.categoryName;
   }

   public void setCategoryName(String categoryName) {
      this.categoryName = categoryName;
   }

   @Column(name = "created_by", nullable = false, length = 100)
   public String getCreatedBy() {
      return this.createdBy;
   }

   public void setCreatedBy(String createdBy) {
      this.createdBy = createdBy;
   }

   @Temporal(TemporalType.TIMESTAMP)
   @Column(name = "created_timestamp", nullable = false, length = 29)
   public Date getCreatedTimestamp() {
      return this.createdTimestamp;
   }

   public void setCreatedTimestamp(Date createdTimestamp) {
      this.createdTimestamp = createdTimestamp;
   }

   @OneToMany(fetch = FetchType.LAZY, mappedBy = "category")
   public Set<RecipeCategory> getRecipeCategories() {
      return this.recipeCategories;
   }

   public void setRecipeCategories(Set<RecipeCategory> recipeCategories) {
      this.recipeCategories = recipeCategories;
   }

}
