package com.michaelhoffmantech.recipemanager.recipedataservice.domain;
// Generated Feb 13, 2017 4:02:01 PM by Hibernate Tools 5.2.0.CR1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Recipeinstruction generated by hbm2java
 */
@Entity
@Table(name = "recipe_instruction")
public class RecipeInstruction implements java.io.Serializable {

   private static final long serialVersionUID = -6094925786732680925L;

   private int recipeInstructionId;
   private Recipe recipe;
   private String createdBy;
   private Date createdTimestamp;
   private String instructionValue;
   private int sequenceNumber;

   public RecipeInstruction() {
   }

   public RecipeInstruction(int recipeInstructionId, Recipe recipe, String createdBy,
         Date createdTimestamp, String instructionValue, int sequenceNumber) {
      this.recipeInstructionId = recipeInstructionId;
      this.recipe = recipe;
      this.createdBy = createdBy;
      this.createdTimestamp = createdTimestamp;
      this.instructionValue = instructionValue;
      this.sequenceNumber = sequenceNumber;
   }

   @Id
   @SequenceGenerator(name = "recipe_instruction_recipe_instruction_id_seq",
         sequenceName = "recipe_instruction_recipe_instruction_id_seq",
         allocationSize = 1)
   @GeneratedValue(strategy = GenerationType.SEQUENCE,
         generator = "recipe_instruction_recipe_instruction_id_seq")
   @Column(name = "recipe_instruction_id", unique = true, nullable = false)
   public int getRecipeInstructionId() {
      return this.recipeInstructionId;
   }

   public void setRecipeInstructionId(int recipeInstructionId) {
      this.recipeInstructionId = recipeInstructionId;
   }

   @ManyToOne(fetch = FetchType.LAZY)
   @JoinColumn(name = "recipe_id", nullable = false)
   public Recipe getRecipe() {
      return this.recipe;
   }

   public void setRecipe(Recipe recipe) {
      this.recipe = recipe;
   }

   @Column(name = "created_by", nullable = false, length = 100)
   public String getCreatedBy() {
      return this.createdBy;
   }

   public void setCreatedBy(String createdBy) {
      this.createdBy = createdBy;
   }

   @Temporal(TemporalType.TIMESTAMP)
   @Column(name = "created_timestamp", nullable = false, length = 29)
   public Date getCreatedTimestamp() {
      return this.createdTimestamp;
   }

   public void setCreatedTimestamp(Date createdTimestamp) {
      this.createdTimestamp = createdTimestamp;
   }

   @Column(name = "instruction_value", nullable = false)
   public String getInstructionValue() {
      return this.instructionValue;
   }

   public void setInstructionValue(String instructionValue) {
      this.instructionValue = instructionValue;
   }

   @Column(name = "sequence_number", nullable = false)
   public int getSequenceNumber() {
      return this.sequenceNumber;
   }

   public void setSequenceNumber(int sequenceNumber) {
      this.sequenceNumber = sequenceNumber;
   }

}
