package com.michaelhoffmantech.recipemanager.recipedataservice.domain;
// Generated Feb 13, 2017 4:02:01 PM by Hibernate Tools 5.2.0.CR1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Recipereview generated by hbm2java
 */
@Entity
@Table(name = "recipe_review")
public class RecipeReview implements java.io.Serializable {

   private static final long serialVersionUID = -7117495012693342988L;

   private int recipeReviewId;
   private Recipe recipe;
   private String createdBy;
   private Date createdTimestamp;
   private String reviewComment;
   private Integer reviewRating;
   private int userId;

   public RecipeReview() {
   }

   public RecipeReview(int recipeReviewId, Recipe recipe, String createdBy,
         Date createdTimestamp, int userId) {
      this.recipeReviewId = recipeReviewId;
      this.recipe = recipe;
      this.createdBy = createdBy;
      this.createdTimestamp = createdTimestamp;
      this.userId = userId;
   }

   public RecipeReview(int recipeReviewId, Recipe recipe, String createdBy,
         Date createdTimestamp, String reviewComment, Integer reviewRating, int userId) {
      this.recipeReviewId = recipeReviewId;
      this.recipe = recipe;
      this.createdBy = createdBy;
      this.createdTimestamp = createdTimestamp;
      this.reviewComment = reviewComment;
      this.reviewRating = reviewRating;
      this.userId = userId;
   }

   @Id
   @SequenceGenerator(name = "recipe_review_recipe_review_id_seq",
         sequenceName = "recipe_review_recipe_review_id_seq", allocationSize = 1)
   @GeneratedValue(strategy = GenerationType.SEQUENCE,
         generator = "recipe_review_recipe_review_id_seq")
   @Column(name = "recipe_review_id", unique = true, nullable = false)
   public int getRecipeReviewId() {
      return this.recipeReviewId;
   }

   public void setRecipeReviewId(int recipeReviewId) {
      this.recipeReviewId = recipeReviewId;
   }

   @ManyToOne(fetch = FetchType.LAZY)
   @JoinColumn(name = "recipe_id", nullable = false)
   public Recipe getRecipe() {
      return this.recipe;
   }

   public void setRecipe(Recipe recipe) {
      this.recipe = recipe;
   }

   @Column(name = "created_by", nullable = false, length = 100)
   public String getCreatedBy() {
      return this.createdBy;
   }

   public void setCreatedBy(String createdBy) {
      this.createdBy = createdBy;
   }

   @Temporal(TemporalType.TIMESTAMP)
   @Column(name = "created_timestamp", nullable = false, length = 29)
   public Date getCreatedTimestamp() {
      return this.createdTimestamp;
   }

   public void setCreatedTimestamp(Date createdTimestamp) {
      this.createdTimestamp = createdTimestamp;
   }

   @Column(name = "review_comment")
   public String getReviewComment() {
      return this.reviewComment;
   }

   public void setReviewComment(String reviewComment) {
      this.reviewComment = reviewComment;
   }

   @Column(name = "review_rating")
   public Integer getReviewRating() {
      return this.reviewRating;
   }

   public void setReviewRating(Integer reviewRating) {
      this.reviewRating = reviewRating;
   }

   @Column(name = "user_id", nullable = false)
   public int getUserId() {
      return this.userId;
   }

   public void setUserId(int userId) {
      this.userId = userId;
   }

}
