package com.michaelhoffmantech.recipemanager.recipedataservice.domain;
// Generated Feb 13, 2017 4:02:01 PM by Hibernate Tools 5.2.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Recipe generated by hbm2java
 */
@Entity
@Table(name = "recipe")
public class Recipe implements java.io.Serializable {

   private static final long serialVersionUID = -2396413094160491864L;

   private int recipeId;
   private String createdBy;
   private Date createdTimestamp;
   private boolean isActive;
   private String recipeName;
   private int userId;
   private Set<RecipeCategory> recipeCategories = new HashSet<RecipeCategory>(0);
   private Set<RecipeInstruction> recipeInstructions = new HashSet<RecipeInstruction>(0);
   private Set<RecipeIngredient> recipeIngredients = new HashSet<RecipeIngredient>(0);
   private Set<RecipePicture> recipePictures = new HashSet<RecipePicture>(0);
   private Set<RecipeAttribute> recipeAttributes = new HashSet<RecipeAttribute>(0);
   private Set<RecipeReview> recipeReviews = new HashSet<RecipeReview>(0);

   public Recipe() {
   }

   public Recipe(int recipeId, String createdBy, Date createdTimestamp, boolean isActive,
         String recipeName, int userId) {
      this.recipeId = recipeId;
      this.createdBy = createdBy;
      this.createdTimestamp = createdTimestamp;
      this.isActive = isActive;
      this.recipeName = recipeName;
      this.userId = userId;
   }

   public Recipe(int recipeId, String createdBy, Date createdTimestamp, boolean isActive,
         String recipeName, int userId, Set<RecipeCategory> recipeCategories,
         Set<RecipeInstruction> recipeInstructions,
         Set<RecipeIngredient> recipeIngredients, Set<RecipePicture> recipePictures,
         Set<RecipeAttribute> recipeAttributes, Set<RecipeReview> recipeReviews) {
      this.recipeId = recipeId;
      this.createdBy = createdBy;
      this.createdTimestamp = createdTimestamp;
      this.isActive = isActive;
      this.recipeName = recipeName;
      this.userId = userId;
      this.recipeCategories = recipeCategories;
      this.recipeInstructions = recipeInstructions;
      this.recipeIngredients = recipeIngredients;
      this.recipePictures = recipePictures;
      this.recipeAttributes = recipeAttributes;
      this.recipeReviews = recipeReviews;
   }

   @Id
   @SequenceGenerator(name = "recipe_recipe_id_seq",
         sequenceName = "recipe_recipe_id_seq", allocationSize = 1)
   @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "recipe_recipe_id_seq")
   @Column(name = "recipe_id", unique = true, nullable = false)
   public int getRecipeId() {
      return this.recipeId;
   }

   public void setRecipeId(int recipeId) {
      this.recipeId = recipeId;
   }

   @Column(name = "created_by", nullable = false, length = 100)
   public String getCreatedBy() {
      return this.createdBy;
   }

   public void setCreatedBy(String createdBy) {
      this.createdBy = createdBy;
   }

   @Temporal(TemporalType.TIMESTAMP)
   @Column(name = "created_timestamp", nullable = false, length = 29)
   public Date getCreatedTimestamp() {
      return this.createdTimestamp;
   }

   public void setCreatedTimestamp(Date createdTimestamp) {
      this.createdTimestamp = createdTimestamp;
   }

   @Column(name = "is_active", nullable = false)
   public boolean isIsActive() {
      return this.isActive;
   }

   public void setIsActive(boolean isActive) {
      this.isActive = isActive;
   }

   @Column(name = "recipe_name", nullable = false, length = 150)
   public String getRecipeName() {
      return this.recipeName;
   }

   public void setRecipeName(String recipeName) {
      this.recipeName = recipeName;
   }

   @Column(name = "user_id", nullable = false)
   public int getUserId() {
      return this.userId;
   }

   public void setUserId(int userId) {
      this.userId = userId;
   }

   @OneToMany(fetch = FetchType.LAZY, mappedBy = "recipe")
   public Set<RecipeCategory> getRecipeCategories() {
      return this.recipeCategories;
   }

   public void setRecipeCategories(Set<RecipeCategory> recipeCategories) {
      this.recipeCategories = recipeCategories;
   }

   @OneToMany(fetch = FetchType.LAZY, mappedBy = "recipe")
   public Set<RecipeInstruction> getRecipeInstructions() {
      return this.recipeInstructions;
   }

   public void setRecipeInstructions(Set<RecipeInstruction> recipeInstructions) {
      this.recipeInstructions = recipeInstructions;
   }

   @OneToMany(fetch = FetchType.LAZY, mappedBy = "recipe")
   public Set<RecipeIngredient> getRecipeIngredients() {
      return this.recipeIngredients;
   }

   public void setRecipeIngredients(Set<RecipeIngredient> recipeIngredients) {
      this.recipeIngredients = recipeIngredients;
   }

   @OneToMany(fetch = FetchType.LAZY, mappedBy = "recipe")
   public Set<RecipePicture> getRecipePictures() {
      return this.recipePictures;
   }

   public void setRecipePictures(Set<RecipePicture> recipePictures) {
      this.recipePictures = recipePictures;
   }

   @OneToMany(fetch = FetchType.LAZY, mappedBy = "recipe")
   public Set<RecipeAttribute> getRecipeAttributes() {
      return this.recipeAttributes;
   }

   public void setRecipeAttributes(Set<RecipeAttribute> recipeAttributes) {
      this.recipeAttributes = recipeAttributes;
   }

   @OneToMany(fetch = FetchType.LAZY, mappedBy = "recipe")
   public Set<RecipeReview> getRecipeReviews() {
      return this.recipeReviews;
   }

   public void setRecipeReviews(Set<RecipeReview> recipeReviews) {
      this.recipeReviews = recipeReviews;
   }

}
