package com.michaelhoffmantech.recipemanager.recipedataservice.domain;
// Generated Feb 13, 2017 4:02:01 PM by Hibernate Tools 5.2.0.CR1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Recipecategory generated by hbm2java
 */
@Entity
@Table(name = "recipe_category")
public class RecipeCategory implements java.io.Serializable {

   private static final long serialVersionUID = -1174618438147320501L;

   private Integer recipeCategoryId;
   private Category category;
   private Recipe recipe;
   private String createdBy;
   private Date createdTimestamp;

   public RecipeCategory() {
   }

   public RecipeCategory(Integer recipeCategoryId, Category category, Recipe recipe,
         String createdBy, Date createdTimestamp) {
      this.recipeCategoryId = recipeCategoryId;
      this.category = category;
      this.recipe = recipe;
      this.createdBy = createdBy;
      this.createdTimestamp = createdTimestamp;
   }

   @Id
   @SequenceGenerator(name = "recipe_category_recipe_category_id_seq",
         sequenceName = "recipe_category_recipe_category_id_seq", allocationSize = 1)
   @GeneratedValue(strategy = GenerationType.SEQUENCE,
         generator = "recipe_category_recipe_category_id_seq")
   @Column(name = "recipe_category_id", unique = true, nullable = false)
   public Integer getRecipeCategoryId() {
      return this.recipeCategoryId;
   }

   public void setRecipeCategoryId(Integer recipeCategoryId) {
      this.recipeCategoryId = recipeCategoryId;
   }

   @ManyToOne(fetch = FetchType.LAZY)
   @JoinColumn(name = "category_id", nullable = false)
   public Category getCategory() {
      return this.category;
   }

   public void setCategory(Category category) {
      this.category = category;
   }

   @ManyToOne(fetch = FetchType.LAZY)
   @JoinColumn(name = "recipe_id", nullable = false)
   public Recipe getRecipe() {
      return this.recipe;
   }

   public void setRecipe(Recipe recipe) {
      this.recipe = recipe;
   }

   @Column(name = "created_by", nullable = false, length = 100)
   public String getCreatedBy() {
      return this.createdBy;
   }

   public void setCreatedBy(String createdBy) {
      this.createdBy = createdBy;
   }

   @Temporal(TemporalType.TIMESTAMP)
   @Column(name = "created_timestamp", nullable = false, length = 29)
   public Date getCreatedTimestamp() {
      return this.createdTimestamp;
   }

   public void setCreatedTimestamp(Date createdTimestamp) {
      this.createdTimestamp = createdTimestamp;
   }

}
